name: json_server
description: >-
  Launch JSON server for web and mobile apps development from CLI without complicated backend setup for Dart
  and Flutter development.
version: 1.0.0+2
author: Pete Houston <contact@petehouston.com>
homepage: https://github.com/petehouston/dart-json-server
repository: https://github.com/petehouston/dart-json-server
issue_tracker: https://github.com/petehouston/dart-json-server/issues


environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  jserver: main
