name: json_server
description: Handy JSON server for web and mobile apps development.
version: 0.0.1+1
homepage: https://github.com/petehouston/dart-json-server
author: Pete Houston <contact@petehouston.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  jserver: main
